Repository AY2122S2-CS2103T-T17-3/tp, pull requests merged in 2022-03, with the labels that each got.

#18 Add Jun Kang's Skeletal PPP
  docs/team/ngjunkang.md
Labels: documentation

#16 Update glossary of Developer Guide v1.1
  docs/DeveloperGuide.md
Labels: documentation

#23 Add Kexin's Skeletal PPP
  docs/team/cashewnade.md
Labels: documentation

#20 Update Non-Functional Requirements
  docs/DeveloperGuide.md
Labels: documentation

#19 Update user profile,stories and value proposition for v1.1
  docs/DeveloperGuide.md
Labels: documentation

#17 README and AboutUs for v1.1
  README.md
  docs/AboutUs.md
  docs/images/Ui.png
  docs/images/bloodofme.png
  docs/images/cashewnade.png
  docs/images/ngjunkang.png
  docs/images/pyk595.png
  docs/team/bloodofme.md
  docs/team/johndoe.md
Labels: documentation

#21 Add Yuan Ker's Skeletal PPP
  docs/team/pyk595.md
Labels: documentation

#15 Update use cases of Developer Guide v1.1
  docs/DeveloperGuide.md
Labels: documentation

#22 Update User Guide
  docs/UserGuide.md
Labels: documentation

#24 Update Nadine's skeletal PPP
  docs/team/bloodofme.md
Labels: documentation

#26 Update Nadine's PPP for v1.1
  docs/team/bloodofme.md
Labels: documentation

#27 Update _config.yml
  docs/_config.yml
Labels: documentation

#32 Update help feature
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#30 Add custom date model
  src/main/java/seedu/address/model/date/DocumentedDate.java
  src/test/java/seedu/address/model/date/DocumentedDateTest.java
Labels: type.Enhancement

#43 Add command to filter contacts by a tag
  src/main/java/seedu/address/logic/commands/HashtagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HashtagCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonWithTagPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/HashtagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/HashtagCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PersonWithTagPredicateTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Task, priority.High

#44 Add command to add a tag to contact
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#45 Add birthdate field to contacts
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/date/BirthDate.java
  src/main/java/seedu/address/model/date/DocumentedDate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/date/BirthDateTest.java
  src/test/java/seedu/address/model/date/DocumentedDateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#46 Add recents feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/ContactedCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ContactedCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/date/RecentDate.java
  src/main/java/seedu/address/model/person/Description.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ContactedCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ContactedCommandParserTest.java
  src/test/java/seedu/address/model/date/RecentDateTest.java
  src/test/java/seedu/address/model/person/DescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#57 Update test cases for ContactedCommand class
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Description.java
  src/test/java/seedu/address/logic/commands/ContactedCommandTest.java
  src/test/java/seedu/address/logic/parser/ContactedCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Task

#59 Add Birthday Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/BirthdayCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HashtagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/BirthdayCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, type.Story, priority.High

#65 Add backup function
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
Labels: type.Bug, priority.High

#75 Add support to show all tags
  src/main/java/seedu/address/logic/commands/ListTagsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tag/ReadOnlyUniqueTagList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTagsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
Labels: type.Enhancement, priority.High

#74 Update how Description and RecentDate is parsed into ContactedInfo
  src/main/java/seedu/address/logic/parser/AddContactedCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/contactedinfo/ContactedInfo.java
  src/main/java/seedu/address/model/date/RecentDate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedContactedInfo.java
  src/test/java/seedu/address/logic/commands/AddContactedInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddContactedInfoCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/contactedinfo/ContactedInfoTest.java
Labels: type.Task, priority.High

#81 Update use case inclusion format
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#79 Clean up tagging feature improvement
  src/main/java/seedu/address/logic/commands/HashtagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HashtagCommandParser.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/HashtagCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HashtagCommandParserTest.java
Labels: type.Task, priority.High

#86 Delete Trailing Whitespaces
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High

#84 Add logs feature to recents feature
  src/main/java/seedu/address/logic/commands/ListContactRemindersCommand.java
  src/main/java/seedu/address/logic/commands/ListContactedInfoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListContactedInfoCommandParser.java
  src/test/java/seedu/address/logic/commands/ListContactedInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/ListContactedInfoCommandParserTest.java
Labels: priority.High

#88 Add use case for birthdays command
  docs/DeveloperGuide.md
Labels: documentation

#91 Update Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High

#89 Implement delete feature for Recents feature
  src/main/java/seedu/address/logic/commands/AddContactedInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactedInfoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListContactedInfoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteContactedInfoCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/DeleteContactedInfoCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteContactedInfoCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#92 Update ContactedInfo related Commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteContactedInfoCommand.java
  src/main/java/seedu/address/logic/commands/ListContactedInfoCommand.java
  src/main/java/seedu/address/logic/parser/DeleteContactedInfoCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteContactedInfoCommandTest.java
  src/test/java/seedu/address/logic/commands/ListContactedInfoCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task, priority.High

#98 Update User Guide's usage section
  docs/UserGuide.md
Labels: documentation, priority.High

#99 Update user guide
  docs/UserGuide.md
  docs/index.md
Labels: documentation, priority.High

#103 Update User Guide feature section
  docs/UserGuide.md
Labels: documentation, priority.High

#105 Fix UG for pdf format
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: documentation, priority.High

#107 Fix title, add page break
  docs/UserGuide.md
Labels: documentation, priority.High

#109 Add check for Recent Date Objects
  src/main/java/seedu/address/model/contactedinfo/ContactedInfo.java
  src/main/java/seedu/address/model/date/RecentDate.java
  src/test/java/seedu/address/model/date/RecentDateTest.java
Labels: type.Bug, priority.High

#111 Add UniqueTagList to Model UML diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.High

#113 Update AddContactedInfoCommandParserTest
  src/test/java/seedu/address/logic/parser/AddContactedInfoCommandParserTest.java
Labels: type.Task, priority.High

#115 Localise examples for user guide
  docs/UserGuide.md
Labels: type.Task

#119 Branch resolve duplicate recent dates
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddContactedInfoCommand.java
  src/main/java/seedu/address/logic/parser/AddContactedCommandParser.java
  src/main/java/seedu/address/model/date/RecentDate.java
  src/main/java/seedu/address/model/description/Description.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddContactedInfoCommandTest.java
Labels: type.Task, priority.High, severity.High

#120 Update User Guide
  docs/UserGuide.md
Labels: documentation, priority.High

#123 Update UI for more command display space
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High

#124 Fix text formatting in result display
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddContactedInfoCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/BirthdayCommand.java
  src/main/java/seedu/address/logic/commands/ContactedOutsideRangeCommand.java
  src/main/java/seedu/address/logic/commands/ContactedWithinRangeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteContactedInfoCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HashtagCommand.java
  src/main/java/seedu/address/logic/commands/ListContactedInfoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/contactedinfo/ContactedInfo.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddContactedInfoCommandTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
Labels: type.Task, priority.High

#126 Update shadowJar archiveName to AIA.jar
  build.gradle
Labels: type.Task, priority.High

#129 Add check for Description
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddContactedInfoCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/description/Description.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Task, priority.High
