Repository AY2122S2-CS2103T-T17-3/tp, pull requests merged in 2022-04, with the labels that each got.

#132 Update user guide with relevent screenshots.
  docs/UserGuide.md
  docs/images/userguideimages/AddCommandWithTag.png
  docs/images/userguideimages/AddCommandWithoutTag.png
  docs/images/userguideimages/AfterCommand.png
  docs/images/userguideimages/BirthdayCommand.png
  docs/images/userguideimages/DeleteCommand.png
  docs/images/userguideimages/EditCommandWithTag.png
  docs/images/userguideimages/EditCommandWithoutTag.png
  docs/images/userguideimages/FindCommand.png
  docs/images/userguideimages/FindCommandMultiple.png
  docs/images/userguideimages/ForgetCommand.png
  docs/images/userguideimages/HashtagTag.png
  docs/images/userguideimages/ListCommand.png
  docs/images/userguideimages/LogCommand.png
  docs/images/userguideimages/LogsCommand.png
  docs/images/userguideimages/RemindCommand.png
  docs/images/userguideimages/ReminderCommand.png
  docs/images/userguideimages/RemindersCommand.png
  docs/images/userguideimages/TagCommand.png
  docs/images/userguideimages/TagsCommand.png
  docs/images/userguideimages/UnlogCommand.png
  docs/images/userguideimages/UntagCommand.png
  docs/images/userguideimages/WithinCommand.png
Labels: documentation

#163 Update AddCommand MESSAGE_USAGE
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, priority.High, priority.Medium

#164 Fix tag in ToC and command summary
  docs/UserGuide.md
Labels: type.Bug, documentation, priority.High, severity.Low

#165 Resolve UserGuide issues from PED.
  docs/UserGuide.md
Labels: severity.Low

#172 Add Tag implementation in Developer's Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddTagsSequenceDiagram.puml
  docs/diagrams/RemoveTagsSequenceDiagram.puml
  docs/diagrams/SetPersonSequenceDiagram.puml
  docs/diagrams/TagClassDiagram.puml
  docs/images/AddTagsSequenceDiagram.png
  docs/images/RemoveTagsSequenceDiagram.png
  docs/images/SetPersonSequenceDiagram.png
  docs/images/TagClassDiagram.png
Labels: documentation, priority.High

#167 Fix isValidEmail
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug, priority.High

#170 Add UML diagrams for date type classes
  docs/DeveloperGuide.md
  docs/diagrams/BirthDateCreationSequenceDiagram.puml
  docs/diagrams/DocumentedDateClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/RecentDateCreationSequenceDiagram.puml
  docs/diagrams/ReminderDateCreationSequenceDiagram.puml
  docs/images/BirthDateCreationSequenceDiagram.png
  docs/images/DocumentedDateClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/RecentDateCreationSequenceDiagram.png
  docs/images/ReminderDateCreationSequenceDiagram.png
Labels: documentation

#178 Add tag constraint in User Guide
  docs/UserGuide.md
Labels: type.Bug, documentation, priority.High, severity.Medium

#177 Add in-page hyperlinks to date format
  docs/UserGuide.md
Labels: documentation, priority.High

#169 Fix User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, documentation, priority.High

#183 Change AB3 links to project links
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#192 Fix ToC
  docs/UserGuide.md
Labels: type.Bug, documentation

#193 Fix ToC
  docs/UserGuide.md
Labels: type.Bug, documentation

#179 Update Implementation for Date Creation in DG
  docs/DeveloperGuide.md
  docs/diagrams/ReadAddressBookSequenceDiagram.puml
  docs/images/ReadAddressBookSequenceDiagram.png
Labels: documentation

#195 Add note to address navigability from UniqueTagList to Tag in model
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: documentation, type.Task, priority.High

#196 Update Jun Kang's PPP draft
  docs/team/ngjunkang.md
Labels: documentation, type.Task, priority.High

#189 Update Yuan Ker's PPP
  docs/team/pyk595.md
Labels: documentation

#199 Update Nadine's draft PPP
  docs/team/bloodofme.md
  src/main/java/seedu/address/storage/JsonAdaptedContactedInfo.java
Labels: documentation, type.Task, priority.Medium

#203 Fix minor typos, improve English writing in User Guide
  docs/UserGuide.md
Labels: type.Bug, documentation, priority.High, severity.VeryLow

#204 Add UI markup for GUI
  docs/UserGuide.md
  docs/images/userguideimages/AddCommandWithTag.png
  docs/images/userguideimages/AddCommandWithoutTag.png
  docs/images/userguideimages/AfterCommand.png
  docs/images/userguideimages/EditCommandWithTag.png
  docs/images/userguideimages/EditCommandWithoutTag.png
  docs/images/userguideimages/FindCommand.png
  docs/images/userguideimages/FindCommandMultiple.png
  docs/images/userguideimages/HashtagTag.png
  docs/images/userguideimages/ListCommand.png
  docs/images/userguideimages/LogCommand.png
  docs/images/userguideimages/LogsCommand.png
  docs/images/userguideimages/TagCommand.png
  docs/images/userguideimages/TagsCommand.png
  docs/images/userguideimages/UIMarkup.png
  docs/images/userguideimages/UnlogCommand.png
  docs/images/userguideimages/UntagCommand.png
  docs/images/userguideimages/WithinCommand.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug, documentation

#202 Update DG and UML Diagrams for ContactedInfo feature
  docs/DeveloperGuide.md
  docs/diagrams/AddContactedInfoCommandParserSeqDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ContactedInfo.puml
  docs/diagrams/DescriptionSeqDiagram.puml
  docs/diagrams/ModelContactedInfo.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/AddContactedInfoCommandParserSeqDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ContactedInfo.png
  docs/images/DescriptionSeqDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelContactedInfo.png
  docs/images/StorageClassDiagram.png
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/AddContactedInfoCommand.java
Labels: documentation

#205 remove deprecated format
  docs/team/pyk595.md
Labels: documentation

#208 Update deprecated link in DevOps.md
  docs/DevOps.md
Labels: documentation, priority.High

#209 Add badge
  docs/index.md
Labels: type.Bug, documentation

#213 Remove square brackets in usage
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
Labels: type.Bug, priority.High

#221 Update User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
Labels: type.Bug, documentation, priority.High

#219 ContactedInfo date can be before person's birthdate
  src/main/java/seedu/address/logic/commands/AddContactedInfoCommand.java
  src/main/java/seedu/address/model/contactedinfo/ContactedInfo.java
  src/test/java/seedu/address/logic/commands/AddContactedInfoCommandTest.java
  src/test/java/seedu/address/model/description/DescriptionTest.java
Labels: type.Bug

#217 Update Kexin's PPP draft
  docs/team/cashewnade.md
Labels: documentation

#225 Fix Interaction records in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddContactedInfoCommandParserSeqDiagram.puml
  docs/images/AddContactedInfoCommandParserSeqDiagram.png
  src/main/java/seedu/address/logic/parser/AddContactedInfoCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddContactedInfoCommandParserTest.java
Labels: documentation

#228 Add FAQ
  docs/UserGuide.md
  docs/team/pyk595.md
Labels: documentation

#226 Update test cases in DG
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation, type.Task

#230 Update Jun Kang PPP
  docs/team/ngjunkang.md
Labels: documentation, priority.High

#233 Add page breaks
  docs/UserGuide.md
  docs/team/pyk595.md
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#234 Add more page breaks
  docs/UserGuide.md
Labels: documentation, priority.High

#235 Update Nadine's PPP
  docs/team/bloodofme.md
  src/main/java/seedu/address/logic/commands/AddContactedInfoCommand.java
Labels: documentation, severity.Low

#237 Change names to AIAssistant
  docs/UserGuide.md
Labels: documentation

#240 Format DG for pdf
  docs/DeveloperGuide.md
Labels: documentation

#241 Add page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High

#242 Add more page breaks
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#243 May page breaks set us free
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#245 Update diagram to scope, add border
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/SetPersonSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/SetPersonSequenceDiagram.png
Labels: documentation, priority.High

#246 Arrange glossary alphabetically
  docs/DeveloperGuide.md
Labels: documentation

#248 Add case-insensitive in ug
  docs/UserGuide.md
Labels: documentation, priority.High

#249 Add sections
  docs/UserGuide.md
Labels: documentation

#250 Add page breaks
  docs/UserGuide.md
Labels: documentation
